"""empty message

Revision ID: 053c757c7d40
Revises: c25a74f0dc24
Create Date: 2019-01-26 10:30:06.843549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '053c757c7d40'
down_revision = 'c25a74f0dc24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sponsorshiprequest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('requirements', sa.String(), nullable=True),
    sa.Column('brand_preference', sa.String(), nullable=True),
    sa.Column('already_sponsored', sa.String(), nullable=True),
    sa.Column('Category', sa.String(), nullable=True),
    sa.Column('project_type', sa.String(), nullable=True),
    sa.Column('pay', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('first_time', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sponsorshiprequest_end_date'), 'sponsorshiprequest', ['end_date'], unique=False)
    op.create_index(op.f('ix_sponsorshiprequest_start_date'), 'sponsorshiprequest', ['start_date'], unique=False)
    op.create_table('additionalsports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profession_type', sa.Text(), nullable=True),
    sa.Column('game', sa.Text(), nullable=True),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('visitors', sa.Text(), nullable=True),
    sa.Column('event_scope', sa.Text(), nullable=True),
    sa.Column('visibility_material', sa.Text(), nullable=True),
    sa.Column('communication_plan', sa.Text(), nullable=True),
    sa.Column('digital_return', sa.Text(), nullable=True),
    sa.Column('logo', sa.Text(), nullable=True),
    sa.Column('hospitality', sa.Text(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('sponsor_request_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sponsor_request_id'], ['sponsorshiprequest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sponsorshipaccept',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method', sa.Text(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('sponsor_request_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sponsor_request_id'], ['sponsorshiprequest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sponsorshipaccept_timestamp'), 'sponsorshipaccept', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sponsorshipaccept_timestamp'), table_name='sponsorshipaccept')
    op.drop_table('sponsorshipaccept')
    op.drop_table('additionalsports')
    op.drop_index(op.f('ix_sponsorshiprequest_start_date'), table_name='sponsorshiprequest')
    op.drop_index(op.f('ix_sponsorshiprequest_end_date'), table_name='sponsorshiprequest')
    op.drop_table('sponsorshiprequest')
    # ### end Alembic commands ###
