"""empty message

Revision ID: 12466abdb4a8
Revises: 4a7e73274b6b
Create Date: 2019-01-16 08:39:18.237421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12466abdb4a8'
down_revision = '4a7e73274b6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sponsership_sponsership_end_date', table_name='sponsership')
    op.drop_index('ix_sponsership_sponsership_start_date', table_name='sponsership')
    op.drop_table('sponsership')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sponsership',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('sponser_type', sa.VARCHAR(), nullable=True),
    sa.Column('sponser_name', sa.VARCHAR(), nullable=True),
    sa.Column('sponsership_start_date', sa.DATETIME(), nullable=True),
    sa.Column('sponsership_end_date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sponsership_sponsership_start_date', 'sponsership', ['sponsership_start_date'], unique=False)
    op.create_index('ix_sponsership_sponsership_end_date', 'sponsership', ['sponsership_end_date'], unique=False)
    # ### end Alembic commands ###
