"""empty message

Revision ID: 1277a86f01ac
Revises: 42d33c64af51
Create Date: 2019-02-17 05:27:24.000098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1277a86f01ac'
down_revision = '42d33c64af51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('updatelikes')
    op.drop_index('ix_updatecomments_timestamp', table_name='updatecomments')
    op.drop_table('updatecomments')
    op.drop_table('updatecommentlikes')
    op.drop_table('update')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('update',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('update_location', sa.VARCHAR(length=50), nullable=False),
    sa.Column('update_category', sa.VARCHAR(length=50), nullable=False),
    sa.Column('update_text', sa.VARCHAR(length=500), nullable=False),
    sa.Column('update_images_', sa.VARCHAR(length=500), nullable=True),
    sa.Column('update_date_posted', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('updatecommentlikes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('update_comment_id', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['update_comment_id'], ['updatecomments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('updatecomments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=True),
    sa.Column('body_html', sa.TEXT(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('disabled', sa.BOOLEAN(), nullable=True),
    sa.Column('author_id', sa.INTEGER(), nullable=True),
    sa.Column('update_id', sa.INTEGER(), nullable=True),
    sa.CheckConstraint('disabled IN (0, 1)'),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['update_id'], ['update.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_updatecomments_timestamp', 'updatecomments', ['timestamp'], unique=False)
    op.create_table('updatelikes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('update_id', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['update_id'], ['update.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
