"""empty message

Revision ID: 157f9d719e88
Revises: 3ad7ce169b46
Create Date: 2019-03-05 10:06:05.632251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '157f9d719e88'
down_revision = '3ad7ce169b46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('image_file', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'image_file')
    # ### end Alembic commands ###
