"""re campaign

Revision ID: 3272036b2e68
Revises: e2d4d075d4a6
Create Date: 2019-01-15 07:20:37.647919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3272036b2e68'
down_revision = 'e2d4d075d4a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaignlikes')
    op.drop_table('campaignsub')
    op.drop_index('ix_campaigninfo_timestamp', table_name='campaigninfo')
    op.drop_table('campaigninfo')
    op.drop_index('ix_campaigncomments_timestamp', table_name='campaigncomments')
    op.drop_table('campaigncomments')
    op.drop_index('ix_campaign_campaign_end_date', table_name='campaign')
    op.drop_index('ix_campaign_campaign_start_date', table_name='campaign')
    op.drop_table('campaign')
    op.drop_table('campaigncommentlikes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigncommentlikes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('campaign_comment_id', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_comment_id'], ['campaigncomments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('campaign_city', sa.VARCHAR(length=50), nullable=False),
    sa.Column('campaign_category', sa.VARCHAR(length=50), nullable=False),
    sa.Column('campaign_title', sa.VARCHAR(length=500), nullable=False),
    sa.Column('campaign_detail', sa.TEXT(), nullable=False),
    sa.Column('campaign_start_date', sa.DATETIME(), nullable=True),
    sa.Column('campaign_end_date', sa.DATETIME(), nullable=True),
    sa.Column('campaign_status', sa.BOOLEAN(), nullable=True),
    sa.Column('campaign_target_age_range', sa.INTEGER(), nullable=True),
    sa.Column('image_file', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_campaign_campaign_start_date', 'campaign', ['campaign_start_date'], unique=False)
    op.create_index('ix_campaign_campaign_end_date', 'campaign', ['campaign_end_date'], unique=False)
    op.create_table('campaigncomments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=True),
    sa.Column('body_html', sa.TEXT(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('disabled', sa.BOOLEAN(), nullable=True),
    sa.Column('author_id', sa.INTEGER(), nullable=True),
    sa.Column('campaign_id', sa.INTEGER(), nullable=True),
    sa.CheckConstraint('disabled IN (0, 1)'),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_campaigncomments_timestamp', 'campaigncomments', ['timestamp'], unique=False)
    op.create_table('campaigninfo',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('goal', sa.TEXT(), nullable=True),
    sa.Column('sub_goals', sa.INTEGER(), nullable=True),
    sa.Column('where_to_redirect', sa.TEXT(), nullable=True),
    sa.Column('learn_more', sa.TEXT(), nullable=True),
    sa.Column('author_id', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('campaign_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_campaigninfo_timestamp', 'campaigninfo', ['timestamp'], unique=False)
    op.create_table('campaignsub',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('campaign_id', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaignlikes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('campaign_id', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
