"""empty message

Revision ID: 32f8d4a2c957
Revises: 58e42abe73de
Create Date: 2019-02-04 18:31:10.475573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32f8d4a2c957'
down_revision = '58e42abe73de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column('image_file', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign', 'image_file')
    # ### end Alembic commands ###
