"""empty message

Revision ID: 378da180932d
Revises: c044efcec9eb
Create Date: 2019-04-06 05:56:46.709906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '378da180932d'
down_revision = 'c044efcec9eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('language')
    op.add_column('user', sa.Column('language', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'language')
    op.create_table('language',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('language', sa.VARCHAR(), nullable=True),
    sa.Column('language_accuracy', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
