"""empty message

Revision ID: 50c35d0b3367
Revises: d9d9cc8c2bbf
Create Date: 2019-01-05 09:49:46.566597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50c35d0b3367'
down_revision = 'd9d9cc8c2bbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brandbrief',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_description', sa.Text(), nullable=True),
    sa.Column('current_market_perception', sa.Text(), nullable=True),
    sa.Column('brand_goals', sa.Text(), nullable=True),
    sa.Column('brand_psychology', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('brandbrief')
    # ### end Alembic commands ###
