"""empty message

Revision ID: 59032ee0d97f
Revises: c19aee0435cd
Create Date: 2018-12-03 06:36:02.839211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59032ee0d97f'
down_revision = 'c19aee0435cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('all')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('all',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
