"""empty message

Revision ID: 6727ccc01261
Revises: 50c35d0b3367
Create Date: 2019-01-05 12:10:27.861688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6727ccc01261'
down_revision = '50c35d0b3367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column('image_file', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign', 'image_file')
    # ### end Alembic commands ###
