"""empty message

Revision ID: 71255af44b10
Revises: c2770f7f9e5c
Create Date: 2018-12-17 10:24:25.145744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71255af44b10'
down_revision = 'c2770f7f9e5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sports')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sports',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('type_of_sports', sa.TEXT(), nullable=True),
    sa.Column('level_of_playing', sa.TEXT(), nullable=True),
    sa.Column('tournament', sa.TEXT(), nullable=True),
    sa.Column('current_team', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
