"""empty message

Revision ID: 812b6b7c6843
Revises: 0040470f901a
Create Date: 2019-02-22 11:28:57.590875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '812b6b7c6843'
down_revision = '0040470f901a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donationupdates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('donationreason_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['donationreason_id'], ['donationreason.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donationupdates_timestamp'), 'donationupdates', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_donationupdates_timestamp'), table_name='donationupdates')
    op.drop_table('donationupdates')
    # ### end Alembic commands ###
