"""empty message

Revision ID: 829813cf1f08
Revises: 1731404cc7aa
Create Date: 2019-01-17 09:30:24.805267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '829813cf1f08'
down_revision = '1731404cc7aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sponsershipcamp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('network', sa.String(), nullable=False),
    sa.Column('product_link', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('price_range', sa.String(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('sponsership_date_posted', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sponsershipapply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('sponsership_id', sa.Integer(), nullable=True),
    sa.Column('social_id', sa.Text(), nullable=True),
    sa.Column('price', sa.Text(), nullable=True),
    sa.Column('concept', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sponsership_id'], ['sponsershipcamp.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sponsershipcomments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('sponsership_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sponsership_id'], ['sponsershipcamp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sponsershipcomments_timestamp'), 'sponsershipcomments', ['timestamp'], unique=False)
    op.create_table('sponsershiplikes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('sponsership_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sponsership_id'], ['sponsershipcamp.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sponsershipcommentlikes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('sponsership_comment_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sponsership_comment_id'], ['sponsershipcomments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sponsershipcommentlikes')
    op.drop_table('sponsershiplikes')
    op.drop_index(op.f('ix_sponsershipcomments_timestamp'), table_name='sponsershipcomments')
    op.drop_table('sponsershipcomments')
    op.drop_table('sponsershipapply')
    op.drop_table('sponsershipcamp')
    # ### end Alembic commands ###
