"""empty message

Revision ID: 870ddf043ce4
Revises: 5b6cbb90c0af
Create Date: 2019-01-16 10:36:25.677756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '870ddf043ce4'
down_revision = '5b6cbb90c0af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sponsership', sa.Column('network', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sponsership', 'network')
    # ### end Alembic commands ###
