"""empty message

Revision ID: 912fe4e42d3d
Revises: 0ef55c225247
Create Date: 2019-02-22 09:50:28.266272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '912fe4e42d3d'
down_revision = '0ef55c225247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('donation')
    op.drop_index('ix_donationreason_end_date', table_name='donationreason')
    op.drop_index('ix_donationreason_start_date', table_name='donationreason')
    op.drop_table('donationreason')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donationreason',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('category', sa.TEXT(), nullable=True),
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('image_file', sa.VARCHAR(length=20), nullable=True),
    sa.Column('goal', sa.TEXT(), nullable=True),
    sa.Column('target_amount', sa.INTEGER(), nullable=True),
    sa.Column('amount_prefilled', sa.INTEGER(), nullable=True),
    sa.Column('end_method', sa.TEXT(), nullable=True),
    sa.Column('link', sa.TEXT(), nullable=True),
    sa.Column('country', sa.TEXT(), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('author_id', sa.INTEGER(), nullable=True),
    sa.Column('start_date', sa.DATETIME(), nullable=True),
    sa.Column('end_date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_donationreason_start_date', 'donationreason', ['start_date'], unique=False)
    op.create_index('ix_donationreason_end_date', 'donationreason', ['end_date'], unique=False)
    op.create_table('donation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('donation_id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=True),
    sa.Column('time_created', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['donation_id'], ['donationreason.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
