"""empty message

Revision ID: 942ab33b9e92
Revises: d3aed841c382
Create Date: 2019-01-04 18:05:51.874866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '942ab33b9e92'
down_revision = 'd3aed841c382'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigninfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('sub_goals', sa.Integer(), nullable=True),
    sa.Column('where_to_redirect', sa.Text(), nullable=True),
    sa.Column('learn_more', sa.Text(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigninfo_timestamp'), 'campaigninfo', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaigninfo_timestamp'), table_name='campaigninfo')
    op.drop_table('campaigninfo')
    # ### end Alembic commands ###
