"""empty message

Revision ID: 9a5bf72109b3
Revises: 504cbc61d08c
Create Date: 2019-02-04 19:40:33.652462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a5bf72109b3'
down_revision = '504cbc61d08c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sponsorshiprequest', sa.Column('image_file', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sponsorshiprequest', 'image_file')
    # ### end Alembic commands ###
