"""empty message

Revision ID: a2c6528c5511
Revises: e7e8b9e9f16e
Create Date: 2019-04-13 07:19:15.789957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2c6528c5511'
down_revision = 'e7e8b9e9f16e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('available_for_sponsorship', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'available_for_sponsorship')
    # ### end Alembic commands ###
