"""terms and condition

Revision ID: b0cb1025bb52
Revises: 0134c42e99dc
Create Date: 2018-12-12 10:28:57.736365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0cb1025bb52'
down_revision = '0134c42e99dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tandc', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'tandc')
    # ### end Alembic commands ###
