"""empty message

Revision ID: b98a054a70f0
Revises: 812b6b7c6843
Create Date: 2019-02-24 18:36:43.149427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b98a054a70f0'
down_revision = '812b6b7c6843'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaignfaq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('que', sa.Text(), nullable=True),
    sa.Column('ans', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaignfaq_timestamp'), 'campaignfaq', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaignfaq_timestamp'), table_name='campaignfaq')
    op.drop_table('campaignfaq')
    # ### end Alembic commands ###
