"""empty message

Revision ID: c044efcec9eb
Revises: 0afd8d4d1dcc
Create Date: 2019-04-05 08:41:28.621727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c044efcec9eb'
down_revision = '0afd8d4d1dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_request', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role_request', 'timestamp')
    # ### end Alembic commands ###
