"""dropdown 2

Revision ID: c2770f7f9e5c
Revises: e3fd3a7be286
Create Date: 2018-12-17 04:31:22.546626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2770f7f9e5c'
down_revision = 'e3fd3a7be286'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('role', sa.TEXT(), nullable=True),
    sa.Column('cat', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
