"""empty message

Revision ID: c7a8fce4c607
Revises: b0c494678fb5
Create Date: 2018-12-12 05:08:57.667367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7a8fce4c607'
down_revision = 'b0c494678fb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_role', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_role')
    # ### end Alembic commands ###
