"""empty message

Revision ID: c86936a066d1
Revises: e0b6407cb3e7
Create Date: 2019-03-02 12:11:32.000219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c86936a066d1'
down_revision = 'e0b6407cb3e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventsfaq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('que', sa.Text(), nullable=True),
    sa.Column('ans', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('events_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['events_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventsfaq_timestamp'), 'eventsfaq', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eventsfaq_timestamp'), table_name='eventsfaq')
    op.drop_table('eventsfaq')
    # ### end Alembic commands ###
