"""added new feilds'

Revision ID: ca5e0cca2984
Revises: b0cb1025bb52
Create Date: 2018-12-15 09:05:34.813229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca5e0cca2984'
down_revision = 'b0cb1025bb52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type_of_sports', sa.Text(), nullable=True),
    sa.Column('level_of_playing', sa.Text(), nullable=True),
    sa.Column('tournament', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('campaign', sa.Column('campaign_status', sa.Boolean(), nullable=True))
    op.add_column('campaign', sa.Column('campaign_target_age_range', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('category', sa.String(length=60), nullable=True))
    op.add_column('user', sa.Column('education_institution', sa.String(length=60), nullable=True))
    op.add_column('user', sa.Column('first_name', sa.String(length=60), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=60), nullable=True))
    op.add_column('user', sa.Column('purpuse', sa.String(length=60), nullable=True))
    op.add_column('user', sa.Column('sub_category', sa.String(length=60), nullable=True))
    op.add_column('user', sa.Column('web_url', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'web_url')
    op.drop_column('user', 'sub_category')
    op.drop_column('user', 'purpuse')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'education_institution')
    op.drop_column('user', 'category')
    op.drop_column('campaign', 'campaign_target_age_range')
    op.drop_column('campaign', 'campaign_status')
    op.drop_table('sports')
    # ### end Alembic commands ###
