"""empty message

Revision ID: d0f5fd66d70b
Revises: 5ff43afa8306
Create Date: 2019-01-30 11:18:03.926614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0f5fd66d70b'
down_revision = '5ff43afa8306'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donationreason',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem', sa.Text(), nullable=True),
    sa.Column('target_amount', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donationreason_end_date'), 'donationreason', ['end_date'], unique=False)
    op.create_index(op.f('ix_donationreason_timestamp'), 'donationreason', ['timestamp'], unique=False)
    op.create_table('donation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('donation_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['donation_id'], ['donationreason.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('donation')
    op.drop_index(op.f('ix_donationreason_timestamp'), table_name='donationreason')
    op.drop_index(op.f('ix_donationreason_end_date'), table_name='donationreason')
    op.drop_table('donationreason')
    # ### end Alembic commands ###
