"""empty message

Revision ID: dfdae831c960
Revises: 99aa0341d08b
Create Date: 2019-01-28 19:51:35.694688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfdae831c960'
down_revision = '99aa0341d08b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sponsorshipacceptinv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method', sa.Text(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('sponsor_request_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sponsor_request_id'], ['sponsorshipapply.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sponsorshipacceptinv_timestamp'), 'sponsorshipacceptinv', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sponsorshipacceptinv_timestamp'), table_name='sponsorshipacceptinv')
    op.drop_table('sponsorshipacceptinv')
    # ### end Alembic commands ###
