"""empty message

Revision ID: e0b6407cb3e7
Revises: 279d6663f9cf
Create Date: 2019-02-28 19:43:08.370858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0b6407cb3e7'
down_revision = '279d6663f9cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sponsorshipfaq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('que', sa.Text(), nullable=True),
    sa.Column('ans', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('sponsor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sponsor_id'], ['sponsorship.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sponsorshipfaq_timestamp'), 'sponsorshipfaq', ['timestamp'], unique=False)
    op.create_table('sponsorshiprequestfaq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('que', sa.Text(), nullable=True),
    sa.Column('ans', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('sponsor_request_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sponsor_request_id'], ['sponsorshiprequest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sponsorshiprequestfaq_timestamp'), 'sponsorshiprequestfaq', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sponsorshiprequestfaq_timestamp'), table_name='sponsorshiprequestfaq')
    op.drop_table('sponsorshiprequestfaq')
    op.drop_index(op.f('ix_sponsorshipfaq_timestamp'), table_name='sponsorshipfaq')
    op.drop_table('sponsorshipfaq')
    op.drop_table('rewards')
    # ### end Alembic commands ###
