"""empty message

Revision ID: e2d4d075d4a6
Revises: a1005135a7b3
Create Date: 2019-01-11 15:05:00.727905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2d4d075d4a6'
down_revision = 'a1005135a7b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donationreason', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_donationreason_end_date'), 'donationreason', ['end_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_donationreason_end_date'), table_name='donationreason')
    op.drop_column('donationreason', 'end_date')
    # ### end Alembic commands ###
