"""empty message

Revision ID: e7e8b9e9f16e
Revises: ac78a6549ab0
Create Date: 2019-04-13 05:13:55.927245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7e8b9e9f16e'
down_revision = 'ac78a6549ab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bio', sa.Column('market', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bio', 'market')
    # ### end Alembic commands ###
